services:
 Unik.Api:
    ports:
      - "32330:80"
    image: ${DOCKER_REGISTRY-}unikapi
    build:
      context: .
      dockerfile: ./Unik.Api/Dockerfile
    environment:
         "ASPNETCORE_ENVIRONMENT": "Development"
         "ConnectionStrings:UnikDbConnection": "Server=10.228.87.186,1433;Database=UnikOnboardingDomain;Trusted_Connection=True;user id=SA; password=XLv92k2zG9;Integrated security=false;MultipleActiveResultSets=true"